# $FreeBSD$

PORTNAME=	libcommuni
DISTVERSIONPREFIX=	v
DISTVERSION=	3.5.0
DISTVERSIONSUFFIX=	-15-gd3e388d
CATEGORIES=	irc

MAINTAINER=	0mp@FreeBSD.org
COMMENT=	xxx

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=	qmake
USE_QT5=	core gui network qml testlib

USE_GITHUB=	yes
GH_ACCOUNT=	communi
GH_TUPLE=	communi:communi-shared:ffa7d49:communishared/src/bin/base/shared

.include <bsd.port.mk>
