--- Cargo.toml.orig	2018-05-07 09:10:21 UTC
+++ Cargo.toml
@@ -15,7 +15,7 @@ ansi_term = "0.9"
 console = "0.6"
 git2 = "0.6"
 error-chain = "0.11"
-directories = "0.9"
+directories = "0.10"
 lazy_static = "1.0"
 
 [dependencies.syntect]
